spring.application.name=employee-directory
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_directory
spring.datasource.username=intern_user
spring.datasource.password=intern123
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration